# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.3.0

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
RUN ./bin/kibana-plugin install https://github.com/nreese/enhanced_tilemap/releases/download/v2017-04-19/enhanced-tilemap-v2017-04-19-5.3.0.zip
